### PR TITLE
Replace fixed class method calls with self(.class) in Unit class

### PR DESCRIPTION
**Pull request by kreintjes**
Replaces every class method call `RubyUnits::Unit.method` with either `method`
(in class methods) or `self.class.method` (in instance methods).

This allows us to override a class method in a sub class and make sure that
every call to that method from it's instances use the new definition.

E.g. we can have a sub class which extends from RubyUnits::Unit and override
eliminate_terms which is then used when dividing or multiplicating instances
of this sub class.

### CODE REVIEW

**Review by olbrich — APPROVED** [review]
👍 Looks good.  Thanks for the contribution!

**Comment by olbrich** [comment]
@kreintjes If you update this with master, I'll merge it in.

**Comment by kreintjes** [comment]
Thanks for the review!

> @kreintjes If you update this with master, I'll merge it in.

Do you prefer a rebase or merge commit? If a merge commit is fine, then I'll press this button:

image

Otherwise it will have to wait a bit longer.

**Comment by olbrich** [comment]
@kreintjes a merge commit is fine, I'm going to squash the branch anyway when I merge it. Go ahead and press the button.

**Comment by kreintjes** [comment]
> @kreintjes a merge commit is fine, I'm going to squash the branch anyway when I merge it. Go ahead and press the button.

I was now in the position to do either (but actually kind of forgot about this :p), but pressing the button is much easier anyway, so done!

**Pull request merged**
